config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to: 'pages#about' #or can do: get 'pages/about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :articles

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories #, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, :through => :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 5, maximum: 3000}
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController # < ApplicationController means from subclass...
  #this new method just initializes @article
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @article = Article.new
  end

  #this method saves article then the attributes are passed to the below params method
  def create
    #debugger
    @article = Article.new(article_params)
    @article.user = current_user
    #@article.save

    if @article.save
      flash[:success] = "Article was successfully created" #handle view in application.html.erb
      redirect_to article_path(@article)
    else
      render 'new'
    end

  end

  def show
    #@article = set_article #don't need to call here since specifying above in the before action
  end

  def edit
    #@article = set_article #don't need to call here since specifying above in the before action
  end

  def update
    @article =
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated" #handle view in application.html.erb
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

def index
  #@articles = Article.all #will show all articles
  @articles = Article.paginate(page: params[:page], per_page: 5) #uses pagiate ruby gem to automatically paginate
end

def destroy
  #@article = set_article #don't need to call here since specifying above in the before action
  @article.destroy
  redirect_to articles_path
  flash[:danger] = "Article deleted"
end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own article"
        redirect_to root_path
      end
    end

end

app/views/articles/_article.html.erb

<% obj.each do |article| %>
  <div class = "row">
    <div class = "col-xs-8 col-xs-offset-2">
      <div class = "well well-lg">
        <div class = "article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class = "article-body">
          <%= truncate(article.description, lenth: 50) %>
          <div class = "article-meta-details">
            <small>Created by: <%= article.user.username if article.user %>,
                              <%= time_ago_in_words(article.created_at) %> ago,
                              last updated: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p> <!--shortcut to show all categories instead of using .each -->
        <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this article", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb

<%= render 'shared/errors', obj: @article %>

<div class = 'row'>
  <div class = 'col-xs-12'>

    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = 'form-group'>
        <div class = 'control-label col-sm-2'>
          <%= f.label :title %>
        </div>
        <div class = 'col-sm-8'>
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus:true %>
        </div>
      </div>
      <div class = 'form-group'>
        <div class = 'control-label col-sm-2'>
          <%= f.label :description %>
        </div>
        <div class = 'col-sm-8'>
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>

      <div class = 'form-group'>
        <div class="row">
          <div class = 'col-sm-offset-2 col-sm-8'>
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
          </div>
        </div>
      </div>

      <div class = 'form-group'>
        <div class = 'col-sm-offset-2 col-sm-10'>
          <%= f.submit class: 'btn btin-primary btn-large' %><br>
        </div>
      </div>
    <% end %>

    <div class = 'col-xs-4 col-xs-offset-2'>
    [ <%= link_to "Cancel and return to article list", articles_path %> | <%= link_to "Add new article", new_article_path %> ]
    </div>

  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit an article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">All articles</h1>

<div align="center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create An Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">
  <%= @article.title %>
</h2>

<div class = "well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4-col-md-offset-4">
          <li>Created by:</li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>

  <h4 class="center"><strong>Description:</strong></h4>
  <hr>
    <%= simple_format(@article.description, {}, wrapper_tag: "p") %>
  </hr>


  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p> <!--shortcut to show all categories instead of using .each -->
  <% end %>

  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>