config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to: 'pages#about' #or can do: get 'pages/about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :articles

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories #, except: [:destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, :through => :article_categories
  validates :name,
              presence: true,
              uniqueness: true,
              length: {minimum: 3, maximum: 25}
  #validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was saved successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Name was successfully updated"
      redirect_to category_path
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
    flash[:danger] = "Category deleted"
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
  <span class="label label-pill label-info">
    <%= link_to category.name, category_path(category) %>
  </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class = 'form-group'>
    <div class = 'control-label col-sm-2'>
      <%= f.label :name %>
    </div>
    <div class = 'col-sm-8'>
      <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus:true %>
    </div>
  </div>
  <div class = 'form-group'>
    <div class = 'col-sm-offset-2 col-sm-10'>
      <%= f.submit(class: 'btn btin-primary btn-large') %><br>
    </div>
  </div>
<% end %>

<div class = 'col-xs-4 col-xs-offset-2'>
[ <%= link_to "Cancel and return to article list", articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing all categories</h1>

<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class = "listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name}", category_path(category) %>
            <!-- <br><%= link_to "Delete this category", category_path(category), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>  -->
          </li>
          <li>
            <small><%= pluralize(category.articles.count, "article") %></small>
          </li>
        <div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
<div align="center">
  <% if logged_in? and current_user.admin? %>
    <div class="row">
      <span class="label label-pill label-info"> <%= link_to "Edit Category Name", edit_category_path(@category) %> </span>
    </div>
  <% end %>
  <%= will_paginate @category_articles%>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
  <%= will_paginate @category_articles %>
</div>